# .github/workflows/release.yaml

name: kong.gateway release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Start Application
        uses: collinkleest/remote-release@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command: |
            docker compose down -v
            KONG_PASSWORD=${{ secrets.KONG_PASSWORD }}
            KONG_DB_USER=${{ secrets.KONG_DB_USER }}
            KONG_DB_PASSWORD=${{ secrets.KONG_DB_PASSWORD }}
            docker compose up -d
