# .github/workflows/release.yaml

name: kong.gateway release

on:
  release:
    types: [published]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Git Pull Latest
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p ~/github && cd ~/github
            git clone https://github.com/collinkleest/kong.gateway.git
            cd ~/github/kong.gateway/
            git pull
  release:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Start Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/github/kong.gateway/
            docker compose down
            docker compose up -d
